version: '3'
services:
  eosCompiler:
    container_name: eosCompiler
    image: "eoscompiler:0.0.1"
  eosNode:
    container_name: eosNode
    network_mode: "host"
    image: "eosnode:0.0.1"
    command: nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --data-dir CONTRACTS_DIR/eosio/data --config-dir CONTRACTS_DIR/eosio/config --access-control-allow-origin='*' --contracts-console --http-validate-host=false --verbose-http-errors -e --http-alias=eosNode:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --filter-on='*' >> nodeos.log 2>&1 &
    ports:
      - "8888:8888"
      - "9876:9876"
