version: '3'
services:
  eosCompiler:
    container_name: eosCompiler
    image: "eoscompiler:0.0.1"
  eosNode:
    stdin_open: true
    tty: true
    container_name: eosNode
    network_mode: "host"
    image: "eosnode:0.0.1"
    ports:
      - "8888:8888"
      - "9876:9876"
    expose:
      - "8888"
